<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>SourceCleaner</AssemblyName>
        <RootNamespace>Jannesen.Tools.SourceCleaner</RootNamespace>

        <TargetFramework>net10.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AutoGenerateBindingRedirects>False</AutoGenerateBindingRedirects>

        <InvariantGlobalization>true</InvariantGlobalization>
        <Nullable>disable</Nullable>

		<OutputPath>bin\</OutputPath>
		
		<IsPublishable>true</IsPublishable>
		<PublishAot>true</PublishAot>
		<PublishSelfContained>true</PublishSelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>full</TrimMode>
        <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
        <StripSymbols>true</StripSymbols>
        <PublishDir>..\output\</PublishDir>

        <Company>Jannesen B.V.</Company>
        <Version>1.11.01.000</Version>
        <Authors>Peter Jannesen</Authors>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

</Project>
